DROP TABLE IF EXISTS log_information;

CREATE TABLE IF NOT EXISTS log_information (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name varchar(100),
    module_name varchar(100),
    method_type SMALLINT,
    level_name SMALLINT,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    message varchar(300),
    CONSTRAINT pk_log_information PRIMARY KEY (id)
    );